language: node_js
sudo: false
node_js:
- '7'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
    - node_modules
script: npm test
env:
  global:
  - CXX=g++-4.8
  - DEBUG='* -babel -eslint*'
