defaults:

  # If no includes are specified, we
  # pull the full list of managed tables from
  # the auth service
  include:
    accounts: !env:list INCLUDE_ACCOUNTS
    tables: !env:list INCLUDE_TABLES

  # Once we have a list of accounts/tables
  # we can exclude ones we don't want to bother
  # with for whatever reason
  ignore:
    accounts: !env:list IGNORE_ACCOUNTS
    tables: !env:list IGNORE_TABLES

  concurrency: !env CONCURRENCY

  s3:
    bucket: !env BUCKET

  taskcluster:
    credentials:
      clientId: !env TASKCLUSTER_CLIENT_ID
      accessToken: !env TASKCLUSTER_ACCESS_TOKEN

  restore:
    aws:
      accessKeyId: !env AWS_ACCESS_KEY_ID
      secretAccessKey: !env AWS_SECRET_ACCESS_KEY
    azure:
      sas: !env AZURE_SAS
    tables: []

production:
  concurrency: 30

  s3:
    bucket: 'taskcluster-backups'

test:
  concurrency: 30
