defaults:

  # If no includes are specified, we
  # pull the full list of managed tables from
  # the auth service
  include:
    # account names to consider
    accounts: !env:list INCLUDE_ACCOUNTS
    # tables (in the form "<account>/<table>") to consider
    tables: !env:list INCLUDE_TABLES
    # containers (in the form "<account>/<container>" to consider
    containers: !env:list INCLUDE_CONTAINERS

  # Once we have a list of accounts/tables
  # we can exclude ones we don't want to bother
  # with for whatever reason
  ignore:
    accounts: !env:list IGNORE_ACCOUNTS
    tables: !env:list IGNORE_TABLES
    containers: !env:list IGNORE_CONTAINERS

  concurrency: !env CONCURRENCY

  s3:
    bucket: !env BUCKET

  taskcluster:
    credentials:
      clientId: !env TASKCLUSTER_CLIENT_ID
      accessToken: !env TASKCLUSTER_ACCESS_TOKEN

  restore:
    aws:
      accessKeyId: !env AWS_ACCESS_KEY_ID
      secretAccessKey: !env AWS_SECRET_ACCESS_KEY
    azure:
      sas: !env AZURE_SAS
    tables:
      # - 'account/tablename'
    containers:
      # - 'account/containername'

  verify:
    table1: !env VERIFY_TABLE_1
    table2: !env VERIFY_TABLE_2
    diffs:  !env:bool VERIFY_DIFFS

production:
  concurrency: 30

  monitoring:
    project: taskcluster-backups
    enable: true
  s3:
    bucket: 'taskcluster-backups'

test:
  concurrency: 30
  monitoring:
    enable: false
