defaults:
  tables: []

  s3:
    bucket: 'taskcluster-backups'
    expiry: '2 weeks'

  taskcluster:
    credentials:
      clientId:       !env TASKCLUSTER_CLIENT_ID
      accessToken:    !env TASKCLUSTER_ACCESS_TOKEN
