defaults:

  # If no includes are specified, we
  # pull the full list of managed tables from
  # the auth service
  include:
    accounts: !env:list INCLUDE_ACCOUNTS
    tables: !env:list INCLUDE_TABLES

  # Once we have a list of accounts/tables
  # we can exclude ones we don't want to bother
  # with for whatever reason
  ignore:
    accounts: !env:list IGNORE_ACCOUNTS
    tables: !env:list IGNORE_TABLES

  concurrency: !env CONCURRENCY

  s3:
    bucket: !env BUCKET

  taskcluster:
    credentials:
      clientId: !env TASKCLUSTER_CLIENT_ID
      accessToken: !env TASKCLUSTER_ACCESS_TOKEN

  restore:
    s3:
      # These are optional and will be fetched from standard
      # aws sdk credentials files or tc-auth if not specified
      aws_access_key_id: !env AWS_ACCESS_KEY
      aws_secret_access_key: !env AWS_SECRET_KEY
    azure:
      accountName: !env AZURE_ACCOUNT_NAME
      accountKey: !env AZURE_ACCOUNT_KEY

production:
  concurrency: 30

  s3:
    bucket: 'taskcluster-backups'

test:
  concurrency: 30
