defaults:
  ignore:
    accounts: !env:list IGNORE_ACCOUNTS
    tables: !env:list IGNORE_TABLES

  concurrency: !env CONCURRENCY

  s3:
    bucket: !env BUCKET

  taskcluster:
    credentials:
      clientId:       !env TASKCLUSTER_CLIENT_ID
      accessToken:    !env TASKCLUSTER_ACCESS_TOKEN

production:
  concurrency: 30

  s3:
    bucket: 'taskcluster-backups'

test:
  concurrency: 30
