defaults:
  include:
    accounts: jungle
    tables: ['foo', 'bar']
  taskcluster:
    credentials:
      clientId:         '...'
      accessToken:      '...'
  s3:
    bucket: 'taskcluster-backups'

  # Only need to define these if doing a restore
  restore:
    aws:
      accessKeyId: '...'
      secretAccessKey: '...'
    azure:
      sas: '...'
    tables:
      - name: 'example-account/example-table'
        remap: false
      - name: 'example-account/example-table-2'
        remap: 'another-account/another-table-name'
    containers:
      - name: 'taskclusterauthv1/auth-production-roles'
        remap: 'jungle/roles-restore'

  verify:
    table1: '...' # e.g. taskclusterv1/TaskclusterGithubBuilds
    table2: '...'

  # Uncomment to set a list of things to backup
  #include:
  #  accounts:
  #    - 'taskclusterv1'
  #  tables:
  #    - 'taskclusterv1/TaskclusterIntegrationOwners'

  # Uncomment to set a list of things to _not_ backup
  #ignore:
  #   accounts:
  #     - 'taskclusterqueuev1'
  #     - 'taskclusterindexv1'
  #     - 'taskclusterv1'
  #     - 'taskcluster'
  #     - 'taskclustersecretsv1'
  #     - 'tcawsprovisioner'
  #   tables:
  #     - 'jungle/TestTaskSizeMembers2'
  #     - 'jungle/LoadTestTasks2'
  #     - 'jungle/TestWorkerTypes'
  #     - 'jungle/LoadTestTaskGroupMembers2'
  #     - 'jungle/LoadTestTaskSizeMembers2'
  #     - 'jungle/TestTasks'
  #     - 'jungle/allowedTable'
  #     - 'jungle/LoadTestTaskGroups2'
  #     - 'jungle/TestTaskGroupMembers2'
  #     - 'jungle/TestTasks2'
  #     - 'jungle/azureEntityTests'
